### ISSUE TITLE
Name?

### ISSUE THREAD

**Issue by frenata** [frenata/xaqt#7]
Are we happy with the existing name? Given that we're breaking with upstream, we can consider changing it, but best to do so early IMO.

**Comment by asmr-hex** [comment]
yeah i think it would be cool to change the name at this point. I think *compilebox* is a tiny bit misleading since it could be mistaken for an environment in which to just compile binaries for certain architectures or something rather than an environment for running arbitrary user code in a safe way.

In terms of name ideas, i'm not really sure, maybe we should all just post some ideas and come to a consensus. Here are some ideas:
* **safehouse**
* **safespace**
* **safexec**
* **cerberus** (? idk maybe too violent -___-)
* **execvault**
* **executy** (omg so bad >_<)
* **xaqt**
* **codekeeper**
* **binkeeper**

some of these names are def really bad, but I think i was trying to come up with something that was more positive than negative-- emphasizing that we are creating a space that promotes safety rather than some sort of quarantine zone or jail cell.

**Comment by frenata** [comment]
Aww, I have a soft spot for `executy` 😆 

What's `xaqt` supposed to mean? "exact"?

`safehouse` and `safespace` are probably the cleanest and most expressive, but I'm not against a cutesy/clever name.

**Comment by asmr-hex** [comment]
lol :)) i do like `executy` too but idk if its like tooooo much haha

`xacty` is also `ex-a-cuty` but spelled in a new startupy style with no vowels cuz thats kewl lol

i dooo like `safehouse` but i do also like cute stuff haha

**Comment by frenata** [comment]
Any thoughts @ericMLindgren ?

**Comment by nefelin** [comment]
Yea! brainstorming names is fun. 
All those sound alright. I also don't thing quarantine based names are terrible. I'm not into safespace, makes me think of emotional boundaries lol. 

I like executy, or executie, or xaqt they all sound adorable. Makes me want to sketch a little mascott

Some more options:
codeoven
doit4me
make4me
remexacute or maybe remex or remexec
sandboxi
runnit
cleanroom

For what it's worth my girlfriend votes for xaqt or runnit, lol. 

What are you guys thinking?

**Comment by frenata** [comment]
**xaqt** is growing on me, and I think neatly (if somewhat cutely ;)) expresses the real thrust of the project.

**Comment by nefelin** [comment]
yeah, I agree... Totally happy to go with that

**Comment by asmr-hex** [comment]
kewl, i like this name :) :+1:
